name: Setup KinD Cluster

on:
  push:
    branches:
      - master

jobs:
  setup_kind:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: KinD start
      id: start_time_kind
      run: |
        echo "start_kind=$(date '+%s')" >> $GITHUB_OUTPUT

    - name: Setup KinD
      run: |
        curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
        chmod +x ./kind
        sudo mv ./kind /usr/local/bin/kind
        kind create cluster --config kind-config.yaml
        
    - name: Setup kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
    #or
    # - name: Create k8s Kind Cluster
    #    uses: helm/kind-action@v1.5.0

    - name: end_time_kind
      id: end_time_kind
      run: |
        echo "end_kind=$(date '+%s')" >> $GITHUB_OUTPUT
  
    - name: Extract Cluster Info
      run: |
        kubectlversion=$(kubectl version --short)
        kindversion=$(kind version)
        pods=$(kubectl get pods -A)
        nodes=$(kind get nodes --name kind)
        echo "kubectl Version: $kubectlversion" > kind-cluster-info.txt
        echo "KinD Version: $kindversion" > kind-cluster-info.txt
        echo "Pods: $pods" >> kind-cluster-info.txt
        echo "Nodes: $nodes" >>> kind-cluster-info.txt
        echo "Time: $((${{steps.end_time_kind.outputs.end_kind}} - ${{steps.start_time_kind.outputs.start_kind}})) seconds"  >> kind-cluster-info.txt
      shell: bash

    - name: Upload KinD Info
      uses: actions/upload-artifact@v3
      with:
        name: kind-cluster-info
        path: kinf-cluster-info.txt

    - name: Cleanup KinD Cluster
      run: |
        kind delete cluster
